from __future__ import annotations

import subprocess
from pathlib import Path

from .easyeffects_export import ICUE_EQ_FREQUENCIES
from .models import AudioPreset, Profile

PIPEWIRE_EQ_CONFIG = Path.home() / ".config" / "pipewire" / "pipewire.conf.d" / "90-linuxcue-virtuoso-eq.conf"
PIPEWIRE_EQ_SINK_NAME = "effect_input.linuxcue_virtuoso_eq"
PIPEWIRE_RESTART_UNITS = (
    "pipewire.service",
    "pipewire-pulse.service",
    "wireplumber.service",
    "pipewire.socket",
    "pipewire-pulse.socket",
)
PIPEWIRE_RUNTIME_UNITS = (
    "pipewire.service",
    "pipewire-pulse.service",
    "pipewire.socket",
    "pipewire-pulse.socket",
)


def write_virtuoso_pipewire_eq(profile: Profile, preset: AudioPreset, target: Path | None = None) -> Path:
    path = target or PIPEWIRE_EQ_CONFIG
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_pipewire_filter_chain_config(profile, preset), encoding="utf-8")
    return path


def restart_pipewire_user_services(timeout: int = 8) -> dict[str, object]:
    available_units = _available_user_units(timeout=timeout)
    restart_units = [unit for unit in PIPEWIRE_RESTART_UNITS if unit in available_units]
    has_pipewire_runtime = any(unit in available_units for unit in PIPEWIRE_RUNTIME_UNITS)
    if not has_pipewire_runtime:
        return {
            "command": ["systemctl", "--user", "list-unit-files"],
            "returncode": 1,
            "stdout": "",
            "stderr": (
                "No PipeWire user service/socket was found. Install or repair PipeWire first: "
                "sudo pacman -S --needed pipewire pipewire-pulse wireplumber"
            ),
            "available_units": sorted(available_units),
            "restart_units": restart_units,
            "ok": False,
        }
    command = ["systemctl", "--user", "restart", *restart_units]
    result = subprocess.run(command, check=False, capture_output=True, text=True, timeout=timeout)
    return {
        "command": command,
        "returncode": result.returncode,
        "stdout": result.stdout.strip(),
        "stderr": result.stderr.strip(),
        "available_units": sorted(available_units),
        "restart_units": restart_units,
        "ok": result.returncode == 0,
    }


def set_default_virtuoso_eq_sink(timeout: int = 4) -> dict[str, object]:
    command = ["pactl", "set-default-sink", PIPEWIRE_EQ_SINK_NAME]
    result = subprocess.run(command, check=False, capture_output=True, text=True, timeout=timeout)
    return {
        "command": command,
        "returncode": result.returncode,
        "stdout": result.stdout.strip(),
        "stderr": result.stderr.strip(),
        "sink": PIPEWIRE_EQ_SINK_NAME,
        "ok": result.returncode == 0,
    }


def _available_user_units(timeout: int = 8) -> set[str]:
    command = ["systemctl", "--user", "list-unit-files", "--type=service", "--type=socket", "--no-legend"]
    result = subprocess.run(command, check=False, capture_output=True, text=True, timeout=timeout)
    units: set[str] = set()
    for line in result.stdout.splitlines():
        parts = line.split()
        if parts:
            units.add(parts[0])
    return units


def _pipewire_filter_chain_config(profile: Profile, preset: AudioPreset) -> str:
    bands = list(zip(ICUE_EQ_FREQUENCIES, _bands(preset)))
    nodes = "\n".join(
        f"""                    {{
                        type = builtin
                        name = band{index}
                        label = bq_peaking
                        control = {{
                            Freq = {frequency:.1f}
                            Q = 1.41
                            Gain = {gain:.1f}
                        }}
                    }}"""
        for index, (frequency, gain) in enumerate(bands, start=1)
    )
    links = "\n".join(
        f'                    {{ output = "band{index}:Out" input = "band{index + 1}:In" }}'
        for index in range(1, len(bands))
    )
    description = _escape(f"linuxcue Virtuoso EQ ({profile.name} / {preset.name})")
    return f"""# Generated by linuxcue. Manual edits can be overwritten.
context.modules = [
    {{
        name = libpipewire-module-filter-chain
        args = {{
            node.description = "{description}"
            media.name = "{description}"
            filter.graph = {{
                nodes = [
{nodes}
                ]
                links = [
{links}
                ]
            }}
            capture.props = {{
                node.name = "effect_input.linuxcue_virtuoso_eq"
                media.class = Audio/Sink
                audio.channels = 2
                audio.position = [ FL FR ]
            }}
            playback.props = {{
                node.name = "effect_output.linuxcue_virtuoso_eq"
                node.passive = true
                audio.channels = 2
                audio.position = [ FL FR ]
            }}
        }}
    }}
]
"""


def _bands(preset: AudioPreset) -> list[float]:
    if preset.bands:
        values = [float(value) for value in preset.bands[:10]]
        values.extend([0.0] * (10 - len(values)))
        return values
    values = [
        preset.bass,
        preset.bass,
        round((preset.bass + preset.mids) / 2),
        preset.mids,
        preset.mids,
        preset.mids,
        round((preset.mids + preset.treble) / 2),
        preset.treble,
        preset.treble,
        preset.treble,
    ]
    return [float(value) for value in values]


def _escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
