from __future__ import annotations

import subprocess
from pathlib import Path

from .easyeffects_export import ICUE_EQ_FREQUENCIES
from .models import AudioPreset, Profile

PIPEWIRE_EQ_CONFIG = Path.home() / ".config" / "pipewire" / "pipewire.conf.d" / "90-linuxcue-virtuoso-eq.conf"


def write_virtuoso_pipewire_eq(profile: Profile, preset: AudioPreset, target: Path | None = None) -> Path:
    path = target or PIPEWIRE_EQ_CONFIG
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_pipewire_filter_chain_config(profile, preset), encoding="utf-8")
    return path


def restart_pipewire_user_services(timeout: int = 8) -> dict[str, object]:
    command = ["systemctl", "--user", "restart", "pipewire.service", "pipewire-pulse.service", "wireplumber.service"]
    result = subprocess.run(command, check=False, capture_output=True, text=True, timeout=timeout)
    return {
        "command": command,
        "returncode": result.returncode,
        "stdout": result.stdout.strip(),
        "stderr": result.stderr.strip(),
        "ok": result.returncode == 0,
    }


def _pipewire_filter_chain_config(profile: Profile, preset: AudioPreset) -> str:
    filters = "\n".join(
        f"                            {{ type = bq_peaking freq = {frequency:.1f} gain = {gain:.1f} q = 1.41 }}"
        for frequency, gain in zip(ICUE_EQ_FREQUENCIES, _bands(preset))
    )
    description = _escape(f"linuxcue Virtuoso EQ ({profile.name} / {preset.name})")
    return f"""# Generated by linuxcue. Manual edits can be overwritten.
context.modules = [
    {{
        name = libpipewire-module-filter-chain
        args = {{
            node.description = "{description}"
            media.name = "{description}"
            filter.graph = {{
                nodes = [
                    {{
                        type = builtin
                        name = eq
                        label = param_eq
                        config = {{
                            filters = [
{filters}
                            ]
                        }}
                    }}
                ]
                inputs = [ "eq:In 1" "eq:In 2" ]
                outputs = [ "eq:Out 1" "eq:Out 2" ]
            }}
            capture.props = {{
                node.name = "effect_input.linuxcue_virtuoso_eq"
                media.class = Audio/Sink
                audio.channels = 2
                audio.position = [ FL FR ]
            }}
            playback.props = {{
                node.name = "effect_output.linuxcue_virtuoso_eq"
                node.passive = true
                audio.channels = 2
                audio.position = [ FL FR ]
            }}
        }}
    }}
]
"""


def _bands(preset: AudioPreset) -> list[float]:
    if preset.bands:
        values = [float(value) for value in preset.bands[:10]]
        values.extend([0.0] * (10 - len(values)))
        return values
    values = [
        preset.bass,
        preset.bass,
        round((preset.bass + preset.mids) / 2),
        preset.mids,
        preset.mids,
        preset.mids,
        round((preset.mids + preset.treble) / 2),
        preset.treble,
        preset.treble,
        preset.treble,
    ]
    return [float(value) for value in values]


def _escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
