KnownDevice(
    slug="void-elite-wireless-gaming-dongle-0a51",
    family="unknown",
    model_hint="CORSAIR VOID ELITE Wireless Gaming Dongle",
    match_tokens=("corsair void elite wireless gaming dongle",),
    protocol="hid",
    support_level="detected",
    next_step="Classify this device family and capture safe HID descriptors before enabling writes.",
    companion_slug=None,
    companion_role=None,
    capabilities=("device-detection",),
    default_product_id=0x0A51,
    default_transport="hid",
    mock_transport="hid",
    mock_serial_number="MOCK-VOID-ELITE-WIRELESS-GAMING-DONGLE-0A51-001",
    mock_notes=("Generated from a linuxcue device report.",),
),
